/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rx_fft.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4d47297e729fc605850f0e0c39b2c3c0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mmwave_bw/rx_fft.h>
// pydoc.h is automatically generated in the build directory
#include <rx_fft_pydoc.h>

void bind_rx_fft(py::module& m)
{

    using rx_fft    = gr::mmwave_bw::rx_fft;


    py::class_<rx_fft, gr::block, gr::basic_block,
        std::shared_ptr<rx_fft>>(m, "rx_fft", D(rx_fft))

        .def(py::init(&rx_fft::make),
           D(rx_fft,make)
        )
        



        ;




}








