/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tx_freq_frame.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(859ca85c5b4fc7be7fdac6a95d61002c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mmwave_bw/tx_freq_frame.h>
// pydoc.h is automatically generated in the build directory
#include <tx_freq_frame_pydoc.h>

void bind_tx_freq_frame(py::module& m)
{

    using tx_freq_frame    = gr::mmwave_bw::tx_freq_frame;


    py::class_<tx_freq_frame, gr::block, gr::basic_block,
        std::shared_ptr<tx_freq_frame>>(m, "tx_freq_frame", D(tx_freq_frame))

        .def(py::init(&tx_freq_frame::make),
           D(tx_freq_frame,make)
        )
        



        ;




}








