/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tx_ifft.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5361bc02f86e104df9f6d0c361f96a92)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mmwave_bw/tx_ifft.h>
// pydoc.h is automatically generated in the build directory
#include <tx_ifft_pydoc.h>

void bind_tx_ifft(py::module& m)
{

    using tx_ifft    = gr::mmwave_bw::tx_ifft;


    py::class_<tx_ifft, gr::block, gr::basic_block,
        std::shared_ptr<tx_ifft>>(m, "tx_ifft", D(tx_ifft))

        .def(py::init(&tx_ifft::make),
           D(tx_ifft,make)
        )
        



        ;




}








