/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-mmwave_bw
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_MMWAVE_BW_API_H
#define INCLUDED_MMWAVE_BW_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_mmwave_bw_EXPORTS
#define MMWAVE_BW_API __GR_ATTR_EXPORT
#else
#define MMWAVE_BW_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_MMWAVE_BW_API_H */
